name: Site Scanning Alerts

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

concurrency:
  group: site-scanning-alerts-${{ github.repository }}
  cancel-in-progress: false

jobs:
  check-alerts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # pin v7.0.1
      - uses: GSA/site-scanning-alert-template@4547eff11cc594e1ab6781723b0a0d864512cee4
        with:
          watchlist: watchlist.txt
          dry_run: false
